### ISSUE TITLE
Symfony Payum Bundle. Custom api usage not working

### ISSUE THREAD

**Issue by StefanGla** [Payum/Payum#748]
I've make a try to implement that example here without modifications.
https://github.com/Payum/Payum/blob/master/docs/symfony/custom-api-usage.md
But it does not work (any more). I'm working with Symfony 3.4.

    Type error: Too few arguments to function Payum\Paypal\ExpressCheckout\Nvp\Api::__construct(), 1 passed in AppBundle/DependencyInjection/PayumFactory.php on line 21 and exactly 3 expected

So how can I pass the http_client and message_factory to the PayumFactory - Class?

**Comment by romainjanvier** [comment]
I'm facing the same issue to use Be2Bill payment Api method.

Did anyone solve this issue to update the doc ?

**Comment by nikaslg** [comment]
Up

**Comment by DevPearl** [comment]
The declaration form shown in the documentation s invalid, see #1014.

**Comment by pierredup** [comment]
This has been fixed in https://github.com/Payum/Payum/pull/1052
